# golangci-lint configuration for Emma CSI Driver

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gocritic
    - revive
    - gosec
    - unparam

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false

  gosec:
    excludes:
      - G104
      - G304

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    - text: "weak cryptographic primitive"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
