# golangci-lint configuration for Emma CSI Driver
version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - bin
    - .git

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - gocritic      # Opinionated Go linter
    - revive        # Fast, configurable linter
    - gosec         # Security checker
    - unparam       # Check for unused function parameters

formatters:
  enable:
    - gofmt         # Check code formatting
    - goimports     # Check import formatting

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/emma-csi-driver

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: false

  gosec:
    excludes:
      - G104
      - G304

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    - text: "weak cryptographic primitive"
      linters:
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
